#!/usr/bin/bash
select choice in CreateDatabase ListDatabases ConnectToDatabases DropDatabase
do
case $choice in
CreateDatabase) . ./CreateDB
;;
ListDatabases) print Adel is the best
;;
ConnectToDatabases) print Tamer is a bad boy
;;
DropDatabase) print Tamer is a bad boy
;;
*) print $REPLY is not one of the choices.
;;
esac
done
